# How To Build MLP  for iris dataset with Scikit-learn

# Step 1: Import the basic libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt


# Import all the necessary libraries for classification
In this case we need sklearn Perceptron which is in linear models group, we need the train split function which is in the metrics group and we need pandas
Step 1:
Step2

Pandas library for handling of data in column and row formart together with retrieving and editing the dataset

In [2]:
# from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split


# from sklearn.preprocessing import StandardScaler as scaler # for preprocessing
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

import pandas as pd

# Step 2: Load the dataset to the platform

The Pandas library has an easy way to load in data, read_csv():

Ensure that you have saved the data file in the same folder as the code. Also ensure it is in CSV format.

NOTE that sklearn has several datasets including iris which is inbuild and has a different way of loading, but for this class we will stick to loading data from an external source which has been downloaded and saved in the same folder as the code

In [3]:
iris = pd.read_csv("iris.csv")

In ordervto view the data, how they are arranged we can use the head() function which shows the first 5 rows of data. To see the last five we use iris.head(-5)

In [4]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.count()

Id               150
SepalLengthCm    150
SepalWidthCm     150
PetalLengthCm    150
PetalWidthCm     150
Species          150
dtype: int64

In [6]:
iris.Species.unique() # Find the unique entries

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# Step 3: Preprocessing
 
This is an important step especially if the dataset is not even, or not normalized. It is also called data cleaning. 
In some cases the data you get is already cleaned therefore you may not need this step.

It is good to scale your all your data both training and testing data before you use it. 

In [7]:
iris.drop('Id', axis=1, inplace=True)

In [8]:
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
from sklearn.preprocessing import StandardScaler  # for preprocessing
scaler = StandardScaler()

In [10]:
# from sklearn.preprocessing import StandardScaler as scaler  # for preprocessing
# scaler = StandardScaler()


# Step 4: Define the inputs and outputs

We now need to define the features(inputs) and labels(outputs). We can do this easily with pandas by slicing the data table and choosing certain rows/columns.

**input/features** are those characteristics of the data that determines the class that they belong e.g color, lenght, weight etc

**output** is the class that they belong e.g positive/negative, 0/1, hot/cold, present/absent etc

You can achieve this by naming all the column names within a double square parenthesis.

Another way to do this using **iloc()**


In [11]:
# Let's tell the dataframe which column we want for the imputs/features.  
inputs = iris[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]

# Let's tell the dataframe which column we want for the target/labels/output.  
output = iris['Species']

In [12]:
inputs.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [13]:
iris.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# Step 5: Split the data to training and testing sets. 
Remember the default percentage is 80% for training and 20% for testing but you can change the percentages using test_size

Assign the split data into diffent arrays

In [14]:
input_train, input_test, output_train, output_test = train_test_split(inputs, output,test_size=0.2)

In [15]:
# MLP = MLPClassifier(hidden_layer_sizes=(30,30,30))

# Now apply the transformations to the data:


In [16]:
# Fit only to the training data
scaler.fit(input_train)

StandardScaler()

In [17]:
input_train = scaler.transform(input_train)
input_test = scaler.transform(input_test)

In [18]:
MLP = MLPClassifier(activation='logistic')

In [19]:
MLP.fit(input_train, output_train)

/Users/ednamilgo/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic')

In [20]:
prediction=MLP.predict(input_test)




# Measure the perfomance

In [21]:
round(MLP.score(input_test, output_test), 4)


0.9333

In [22]:
scaler.fit(input_train)

StandardScaler()

In [23]:

print(confusion_matrix(output_test,prediction))

[[ 9  0  0]
 [ 0  8  2]
 [ 0  0 11]]


In [24]:
print(classification_report(output_test,prediction))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.80      0.89        10
 Iris-virginica       0.85      1.00      0.92        11

       accuracy                           0.93        30
      macro avg       0.95      0.93      0.94        30
   weighted avg       0.94      0.93      0.93        30

